apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-deployment
spec:
  replicas: ____ # Fill this in with: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx